### ISSUE TITLE
Problem with multi-byte languages

### ISSUE THREAD

**Issue by amard** [RAIN-JIANGRAN/I18nTool#1]
Hi, thanks for this great plugin but it has problem with multi-byte language like Persian/Farsi or Arabic.
When the plugin save the translated string to the JSON file all the characters is UNKNOWN char and represented as ' ? ' character after opening JSON file.

for example : 

en => Thank you 
fa  => متشکرم
ar  => شكرا

but after translation and saving to json file :

en => Thank you 
fa  => ??????
ar  => ????

so maybe destination JSON file encoding is in ANSI but not UTF-8 or when you get the string from Google some encoding or decoding required.

**Comment by ra1nj** [comment]
@amard  Sorry for the late reply,  the tool seems working fine when  I selected the Arabic or Persian as target language. so I am wondering is that your IntelliJ IDEA file encoding mode is not in UTF-8 ?  Have you checked the json file in your disk?
